version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      
  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 973434859695.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=973434859695.dkr.ecr.us-east-1.amazonaws.com/demo-repository
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t demo-repository .
      - docker tag demo-repository:latest 973434859695.dkr.ecr.us-east-1.amazonaws.com/demo-repository:latest
      - docker push 973434859695.dkr.ecr.us-east-1.amazonaws.com/demo-repository:latest
      
  post_build:
    commands:
       - echo "Build is Successful"
       
    artifacts:
      files: '**/*'
